[icons]
icons = "material-nf"

[theme]
theme = "modern"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d/%m %T', l:fr_FR) "

[[block]]
block = "battery"
interval = 5
format = "{percentage} {time}"