icons = "awesome"

[theme]
name = "modern"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"

[[block]]
block = "battery"
interval = 5
format = "{percentage} {time}"